In [15]:
import sqlite3
import pandas as pd

In [16]:
conn = sqlite3.connect("college.db")
cursor = conn.cursor()

In [53]:
def run(query):
    display(pd.read_sql_query(query, conn))

In [52]:
cursor.execute("DROP TABLE IF EXISTS Marks")

cursor.execute("""
CREATE TABLE Marks(
    MarkID INTEGER PRIMARY KEY,
    StudentID INTEGER,
    Subject TEXT,
    Marks INTEGER,
    Semester INTEGER,
    FOREIGN KEY(StudentID) REFERENCES Students(StudentID)
)
""")

conn.commit()

In [21]:
run("SELECT * FROM Students")

   StudentID   Name  Age  Gender Department        City
0          1  Rahul   20    Male        CSE   Hyderabad
1          2  Priya   21  Female        ECE  Vijayawada
2          3  Arjun   22    Male        CSE      Guntur
3          4  Sneha   20  Female        EEE   Hyderabad
4          5  Kiran   23    Male       MECH       Vizag
5          6  Divya   21  Female        CSE     Nellore
6          7   Ajay   22    Male        ECE      Kadapa
7          8  Meena   20  Female         IT   Hyderabad
8          9   Ravi   21    Male         IT       Vizag
9         10    Anu   22  Female        CSE      Guntur

In [22]:
run("SELECT * FROM Marks")

   MarkID  StudentID Subject  Marks  Semester
0       1          1  Python     88         1
1       2          2  Python     91         1
2       3          3  Python     79         1
3       4          4  Python     84         1
4       5          5  Python     76         1
5       6          6  Python     95         1
6       7          7  Python     80         1
7       8          8  Python     89         1
8       9          9  Python     82         1
9      10         10  Python     90         1

In [23]:
run("SELECT Name, Age FROM Students")

    Name  Age
0  Rahul   20
1  Priya   21
2  Arjun   22
3  Sneha   20
4  Kiran   23
5  Divya   21
6   Ajay   22
7  Meena   20
8   Ravi   21
9    Anu   22

In [24]:
run("SELECT DISTINCT Department FROM Students")

  Department
0        CSE
1        ECE
2        EEE
3       MECH
4         IT

In [25]:
run("SELECT * FROM Students WHERE Age > 21")

   StudentID   Name  Age  Gender Department    City
0          3  Arjun   22    Male        CSE  Guntur
1          5  Kiran   23    Male       MECH   Vizag
2          7   Ajay   22    Male        ECE  Kadapa
3         10    Anu   22  Female        CSE  Guntur

In [26]:
run("SELECT * FROM Students WHERE Gender='Female'")

   StudentID   Name  Age  Gender Department        City
0          2  Priya   21  Female        ECE  Vijayawada
1          4  Sneha   20  Female        EEE   Hyderabad
2          6  Divya   21  Female        CSE     Nellore
3          8  Meena   20  Female         IT   Hyderabad
4         10    Anu   22  Female        CSE      Guntur

In [27]:
run("SELECT * FROM Students WHERE City='Hyderabad'")

   StudentID   Name  Age  Gender Department       City
0          1  Rahul   20    Male        CSE  Hyderabad
1          4  Sneha   20  Female        EEE  Hyderabad
2          8  Meena   20  Female         IT  Hyderabad

In [28]:
run("SELECT * FROM Marks WHERE Marks>85")

   MarkID  StudentID Subject  Marks  Semester
0       1          1  Python     88         1
1       2          2  Python     91         1
2       6          6  Python     95         1
3       8          8  Python     89         1
4      10         10  Python     90         1

In [29]:
run("SELECT * FROM Marks WHERE Semester=1")

   MarkID  StudentID Subject  Marks  Semester
0       1          1  Python     88         1
1       2          2  Python     91         1
2       3          3  Python     79         1
3       4          4  Python     84         1
4       5          5  Python     76         1
5       6          6  Python     95         1
6       7          7  Python     80         1
7       8          8  Python     89         1
8       9          9  Python     82         1
9      10         10  Python     90         1

In [30]:
run("SELECT Name FROM Students WHERE Department='CSE'")

    Name
0  Rahul
1  Arjun
2  Divya
3    Anu

In [31]:
run("SELECT COUNT(*) AS Total_Students FROM Students")

   Total_Students
0              10

In [32]:
run("SELECT AVG(Marks) AS Average_Marks FROM Marks")

   Average_Marks
0           85.4

In [33]:
run("SELECT MAX(Marks) AS Highest_Marks FROM Marks")

   Highest_Marks
0             95

In [34]:
run("SELECT MIN(Marks) AS Lowest_Marks FROM Marks")

   Lowest_Marks
0            76

In [35]:
run("SELECT SUM(Marks) AS Total_Marks FROM Marks")

   Total_Marks
0          854

In [36]:
run("SELECT Department, COUNT(*) FROM Students GROUP BY Department")

  Department  COUNT(*)
0        CSE         4
1        ECE         2
2        EEE         1
3         IT         2
4       MECH         1

In [37]:
run("SELECT Gender, COUNT(*) FROM Students GROUP BY Gender")

   Gender  COUNT(*)
0  Female         5
1    Male         5

In [38]:
run("SELECT City, COUNT(*) FROM Students GROUP BY City")

         City  COUNT(*)
0      Guntur         2
1   Hyderabad         3
2      Kadapa         1
3     Nellore         1
4  Vijayawada         1
5       Vizag         2

In [39]:
run("SELECT Department, AVG(Age) FROM Students GROUP BY Department")

  Department  AVG(Age)
0        CSE     21.25
1        ECE     21.50
2        EEE     20.00
3         IT     20.50
4       MECH     23.00

In [40]:
run("SELECT Subject, AVG(Marks) FROM Marks GROUP BY Subject")

  Subject  AVG(Marks)
0  Python        85.4

In [41]:
run("SELECT * FROM Marks ORDER BY Marks DESC")

   MarkID  StudentID Subject  Marks  Semester
0       6          6  Python     95         1
1       2          2  Python     91         1
2      10         10  Python     90         1
3       8          8  Python     89         1
4       1          1  Python     88         1
5       4          4  Python     84         1
6       9          9  Python     82         1
7       7          7  Python     80         1
8       3          3  Python     79         1
9       5          5  Python     76         1

In [42]:
run("SELECT * FROM Marks ORDER BY Marks ASC")

   MarkID  StudentID Subject  Marks  Semester
0       5          5  Python     76         1
1       3          3  Python     79         1
2       7          7  Python     80         1
3       9          9  Python     82         1
4       4          4  Python     84         1
5       1          1  Python     88         1
6       8          8  Python     89         1
7      10         10  Python     90         1
8       2          2  Python     91         1
9       6          6  Python     95         1

In [43]:
run("SELECT * FROM Students WHERE Name LIKE 'A%'")

   StudentID   Name  Age  Gender Department    City
0          3  Arjun   22    Male        CSE  Guntur
1          7   Ajay   22    Male        ECE  Kadapa
2         10    Anu   22  Female        CSE  Guntur

In [44]:
run("SELECT * FROM Students WHERE Age BETWEEN 20 AND 22")

   StudentID   Name  Age  Gender Department        City
0          1  Rahul   20    Male        CSE   Hyderabad
1          2  Priya   21  Female        ECE  Vijayawada
2          3  Arjun   22    Male        CSE      Guntur
3          4  Sneha   20  Female        EEE   Hyderabad
4          6  Divya   21  Female        CSE     Nellore
5          7   Ajay   22    Male        ECE      Kadapa
6          8  Meena   20  Female         IT   Hyderabad
7          9   Ravi   21    Male         IT       Vizag
8         10    Anu   22  Female        CSE      Guntur

In [45]:
run("SELECT * FROM Marks WHERE Marks BETWEEN 80 AND 90")

   MarkID  StudentID Subject  Marks  Semester
0       1          1  Python     88         1
1       4          4  Python     84         1
2       7          7  Python     80         1
3       8          8  Python     89         1
4       9          9  Python     82         1
5      10         10  Python     90         1

In [46]:
run("SELECT * FROM Students WHERE City IN ('Hyderabad','Vizag')")

   StudentID   Name  Age  Gender Department       City
0          1  Rahul   20    Male        CSE  Hyderabad
1          4  Sneha   20  Female        EEE  Hyderabad
2          5  Kiran   23    Male       MECH      Vizag
3          8  Meena   20  Female         IT  Hyderabad
4          9   Ravi   21    Male         IT      Vizag

In [47]:
run("SELECT * FROM Marks WHERE Marks IN (88,90,95)")

   MarkID  StudentID Subject  Marks  Semester
0       1          1  Python     88         1
1       6          6  Python     95         1
2      10         10  Python     90         1

In [48]:
run("""
SELECT Students.Name, Marks.Marks
FROM Students
JOIN Marks
ON Students.StudentID = Marks.StudentID
""")

    Name  Marks
0  Rahul     88
1  Priya     91
2  Arjun     79
3  Sneha     84
4  Kiran     76
5  Divya     95
6   Ajay     80
7  Meena     89
8   Ravi     82
9    Anu     90

In [49]:
run("""
SELECT Students.Name, Students.Department, Marks.Subject
FROM Students
JOIN Marks
ON Students.StudentID = Marks.StudentID
""")

    Name Department Subject
0  Rahul        CSE  Python
1  Priya        ECE  Python
2  Arjun        CSE  Python
3  Sneha        EEE  Python
4  Kiran       MECH  Python
5  Divya        CSE  Python
6   Ajay        ECE  Python
7  Meena         IT  Python
8   Ravi         IT  Python
9    Anu        CSE  Python

In [50]:
run("""
SELECT Students.Name, Marks.Marks
FROM Students
JOIN Marks
ON Students.StudentID = Marks.StudentID
ORDER BY Marks.Marks DESC
""")

    Name  Marks
0  Divya     95
1  Priya     91
2    Anu     90
3  Meena     89
4  Rahul     88
5  Sneha     84
6   Ravi     82
7   Ajay     80
8  Arjun     79
9  Kiran     76

In [51]:
run("""
SELECT Students.Name, Marks.Subject, Marks.Marks
FROM Students
JOIN Marks
ON Students.StudentID = Marks.StudentID
""")

    Name Subject  Marks
0  Rahul  Python     88
1  Priya  Python     91
2  Arjun  Python     79
3  Sneha  Python     84
4  Kiran  Python     76
5  Divya  Python     95
6   Ajay  Python     80
7  Meena  Python     89
8   Ravi  Python     82
9    Anu  Python     90

In [54]:
run("""
SELECT Students.Gender, MAX(Marks.Marks)
FROM Students
JOIN Marks
ON Students.StudentID = Marks.StudentID
GROUP BY Students.Gender
""")

Empty DataFrame
Columns: [Gender, MAX(Marks.Marks)]
Index: []

In [55]:
run("""
SELECT Students.Name, Marks.Subject, Marks.Marks
FROM Students
JOIN Marks
ON Students.StudentID = Marks.StudentID
""")

Empty DataFrame
Columns: [Name, Subject, Marks]
Index: []

In [56]:
run("""
SELECT Students.Name, Students.Department, Marks.Marks
FROM Students
JOIN Marks
ON Students.StudentID = Marks.StudentID
WHERE Students.Department='CSE'
""")

Empty DataFrame
Columns: [Name, Department, Marks]
Index: []

In [57]:
cursor.execute("""
UPDATE Students
SET City='Chennai'
WHERE StudentID=1
""")

conn.commit()

In [58]:
cursor.execute("""
UPDATE Marks
SET Marks=99
WHERE StudentID=6
""")

conn.commit()

In [59]:
cursor.execute("""
DELETE FROM Students
WHERE StudentID=5
""")

conn.commit()

In [60]:
run("SELECT * FROM Students")

   StudentID   Name  Age  Gender Department        City
0          1  Rahul   20    Male        CSE     Chennai
1          2  Priya   21  Female        ECE  Vijayawada
2          3  Arjun   22    Male        CSE      Guntur
3          4  Sneha   20  Female        EEE   Hyderabad
4          6  Divya   21  Female        CSE     Nellore
5          7   Ajay   22    Male        ECE      Kadapa
6          8  Meena   20  Female         IT   Hyderabad
7          9   Ravi   21    Male         IT       Vizag
8         10    Anu   22  Female        CSE      Guntur